### ISSUE TITLE
Response body should be recoverable in case of error

### ISSUE THREAD

**Issue by rplati** [r-lib/httr2#295]
In case of error (responses with status codes 4xx and 5xx) the response body may contain valuable information on what happened and/or how to remedy the problem. Example:
```
curl --location 'https://jsonplaceholder.typicode.com/users' \
--header 'Content-Type: application/json' \
--data '{ malformed json }'
```
The response body starting with `SyntaxError: Unexpected token m in JSON at position 2` is informative.

The corresponding `httr2` code displays the status code and text but does not produce the response object from which the response body could be recovered. Am I missing something or is the response body unrecoverable in case of error?

```
> req <- request("https://jsonplaceholder.typicode.com/users") %>% 
+   req_body_raw("{ malformed json }") %>% 
+   req_headers("Content-Type" = "application/json")
> resp <- req_perform(req)
Error in `req_perform()`:
! HTTP 500 Internal Server Error.
Run `rlang::last_error()` to see where the error occurred.
> resp
Error: object 'resp' not found
```

**Comment by mgirlich** [comment]
You have 2 options:

1. Use `last_response()` to get the response (mostly useful in interactive sessions).
2. Use `req_error()` to parse the body

See the example:

``` r
library(httr2)

req <- request("https://jsonplaceholder.typicode.com/users") %>% 
  req_body_raw("{ malformed json }") %>% 
  req_headers("Content-Type" = "application/json") %>% 
  req_error(body = \(resp) {
    as.character(resp_body_html(resp))
  })
resp <- req_perform(req)
#> Error in `req_perform()`:
#> ! HTTP 500 Internal Server Error.
#> • <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
#> <html><body><p>SyntaxError: Unexpected token m in JSON at position 2
#>     at JSON.parse (<anonymous>)
#>     at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)
#>     at /app/node_modules/body-parser/lib/read.js:121:18
#>     at invokeCallback (/app/node_modules/body-parser/node_modules/raw-body/index.js:224:16)
#>     at done (/app/node_modules/body-parser/node_modules/raw-body/index.js:213:7)
#>     at IncomingMessage.onEnd (/app/node_modules/body-parser/node_modules/raw-body/index.js:273:7)
#>     at IncomingMessage.emit (node:events:525:35)
#>     at endReadableNT (node:internal/streams/readable:1358:12)
#>     at processTicksAndRejections (node:internal/process/task_queues:83:21)</anonymous></p></body></html>
#> Backtrace:
#>     ▆
#>  1. └─httr2::req_perform(req)
#>  2.   └─httr2:::handle_resp(req, resp, error_call = error_call)
#>  3.     └─httr2:::resp_abort(resp, body, call = error_call)
#>  4.       └─rlang::abort(...)
last_response()
#> <httr2_response>
#> POST https://jsonplaceholder.typicode.com/users
#> Status: 500 Internal Server Error
#> Content-Type: text/html
#> Body: In memory (667 bytes)
```

<sup>Created on 2023-08-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
